Repository DanielNoord/pydocstringformatter, pull requests merged in 2022-02, with the labels that each got.

#32 Add a testutil class to be able to test formatters easily
  pydocstringformatter/formatting/__init__.py
  pydocstringformatter/formatting/base.py
  pydocstringformatter/testutils/__init__.py
  tests/test_run.py
Labels: enhancement, maintenance

#37 Use ``(de)activate_option`` properties outside of tests
  pydocstringformatter/configuration/formatter_options.py
Labels: maintenance

#30 Add ``SplitSummaryAndDocstringFormatter`` and update testutils
  README.md
  pydocstringformatter/formatting/__init__.py
  pydocstringformatter/formatting/base.py
  pydocstringformatter/formatting/formatter.py
  tests/data/format/summary_splitter/class_docstring.args
  tests/data/format/summary_splitter/class_docstring.py
  tests/data/format/summary_splitter/class_docstring.py.out
  tests/data/format/summary_splitter/function_docstrings.args
  tests/data/format/summary_splitter/function_docstrings.py
  tests/data/format/summary_splitter/function_docstrings.py.out
  tests/data/format/summary_splitter/module_docstring.args
  tests/data/format/summary_splitter/module_docstring.py
  tests/data/format/summary_splitter/module_docstring.py.out
  tests/data/format/summary_splitter/variable_docstring.args
  tests/data/format/summary_splitter/variable_docstring.py
  tests/data/format/summary_splitter/variable_docstring.py.out
  tests/test_formatting.py
  tests/test_run.py
Labels: enhancement

#8 Capitalize the first letter of the docstring
  README.md
  pydocstringformatter/formatting/__init__.py
  pydocstringformatter/formatting/formatter.py
  tests/data/format/capitalization_first_letter/class_docstring.py
  tests/data/format/capitalization_first_letter/class_docstring.py.out
  tests/data/format/capitalization_first_letter/function_docstrings.py
  tests/data/format/capitalization_first_letter/function_docstrings.py.out
  tests/data/format/capitalization_first_letter/module_docstring.py
  tests/data/format/capitalization_first_letter/module_docstring.py.out
  tests/data/format/capitalization_first_letter/uncapitalized_starting_letter.py
  tests/data/format/capitalization_first_letter/uncapitalized_starting_letter.py.out
  tests/data/format/capitalization_first_letter/variable_docstring.py
  tests/data/format/capitalization_first_letter/variable_docstring.py.out
Labels: enhancement

#41 Add ``StripWhitespacesFormatter``
  .pre-commit-config.yaml
  README.md
  pydocstringformatter/formatting/__init__.py
  pydocstringformatter/formatting/formatter.py
  tests/data/format/whitespace_stripper/class_docstring.py
  tests/data/format/whitespace_stripper/class_docstring.py.out
  tests/data/format/whitespace_stripper/function_docstrings.py
  tests/data/format/whitespace_stripper/function_docstrings.py.out
  tests/data/format/whitespace_stripper/module_docstring.py
  tests/data/format/whitespace_stripper/module_docstring.py.out
  tests/data/format/whitespace_stripper/variable_docstring.py
  tests/data/format/whitespace_stripper/variable_docstring.py.out
Labels: enhancement

#40 Special case Sphinx-style titles for ``FinalPeriodFormatter``
  README.md
  pydocstringformatter/formatting/formatter.py
  tests/data/format/final_period/function_title_docstrings.py
  tests/data/format/final_period/function_title_docstrings.py.out
Labels: enhancement

#42 Bump version to ``0.3.0``
  pydocstringformatter/__init__.py
Labels: maintenance

#50 Bump version to ``0.4.0``
  pydocstringformatter/__init__.py
Labels: maintenance

#51 Create a constant for duplicated end of sentence punctuation
  pydocstringformatter/formatting/formatter.py
Labels: maintenance

#52 Add ':' and ';' to allowed punctuation
  pydocstringformatter/formatting/formatter.py
  tests/data/format/final_period/exotic_line_ending.py
  tests/data/format/final_period/exotic_line_ending.py.out
Labels: enhancement

#56 Create ``docs`` and use Readthedocs for hosting
  .gitignore
  .readthedocs.yaml
  docs/Makefile
  docs/_static/custom.css
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements-doc.txt
  requirements-test.txt
Labels: documentation

#55 Separate optional and non-optional formatters in help message
  pydocstringformatter/configuration/arguments_manager.py
  pydocstringformatter/configuration/formatter_options.py
  tests/test_run.py
Labels: documentation, enhancement

#60 Move Contributing to the documentation
  .github/CONTRIBUTING.md
  README.md
  docs/_static/custom.css
  docs/development.rst
  docs/index.rst
Labels: documentation

#62 Backport ``BooleanOptionalAction`` and use it for formatters
  docs/usage.rst
  pydocstringformatter/configuration/arguments_manager.py
  pydocstringformatter/configuration/boolean_option_action.py
  pydocstringformatter/configuration/formatter_options.py
  tests/test_run.py
Labels: documentation, enhancement
