Repository DanielNoord/pydocstringformatter, pull requests merged in 2022-09, with the labels that each got.

#158 Fix adding whitespaces in ``numpydoc`` style to single line docstrings
  docs/usage.rst
  pydocstringformatter/_formatting/__init__.py
  tests/data/format/numpydoc/numpydoc_regression.args
  tests/data/format/numpydoc/numpydoc_regression.py
  tests/data/format/numpydoc/numpydoc_regression.py.out
Labels: bug

#156 fixed toml parser ignoring style
  pydocstringformatter/_configuration/toml_parsing.py
  tests/data/config/valid_toml_numpydoc/pyproject.toml
  tests/data/config/valid_toml_numpydoc/test_package/numpydoc_style.py
  tests/data/config/valid_toml_numpydoc_pep257/pyproject.toml
  tests/data/config/valid_toml_numpydoc_pep257/test_package/numpydoc_style.py
  tests/data/config/valid_toml_pep257/pyproject.toml
  tests/data/config/valid_toml_pep257/test_package/numpydoc_style.py
  tests/test_config.py
Labels: bug

#161 Bugfix/emptyline no whitespace
  .pre-commit-config.yaml
  pydocstringformatter/_formatting/_utils.py
  tests/data/format/no_whitespace_stripper/module_docstring.args
  tests/data/format/no_whitespace_stripper/module_docstring.py
  tests/data/format/no_whitespace_stripper/module_docstring.py.out
Labels: bug

#166 added boolean optional argument support
  README.md
  pydocstringformatter/_configuration/toml_parsing.py
  tests/data/config/non_valid_toml_boolopt/pyproject.toml
  tests/data/config/non_valid_toml_boolopt/test_package/numpydoc_style.py
  tests/data/config/non_valid_toml_boolopt_two/pyproject.toml
  tests/data/config/non_valid_toml_boolopt_two/test_package/numpydoc_style.py
  tests/data/config/valid_toml_boolopt/pyproject.toml
  tests/data/config/valid_toml_boolopt/test_package/numpydoc_style.py
  tests/test_config.py
Labels: enhancement

#171 make black skip files in test data
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#174 renamed 'changed_tokens' ro 'formatted_tokens'
  pydocstringformatter/run.py
Labels: maintenance

#178 abstracted enabled formatters to method
  pydocstringformatter/run.py
Labels: maintenance

#181 Don't add a new line in one-line Numpy docstrings
  pydocstringformatter/_formatting/formatters_numpydoc.py
  tests/data/format/numpydoc/numpydoc_closing_quotes.args
  tests/data/format/numpydoc/numpydoc_closing_quotes.py
  tests/data/format/numpydoc/numpydoc_closing_quotes.py.out
Labels: bug
