Repository DanielNoord/pydocstringformatter, pull requests merged in 2022-01, with the labels that each got.

#9 Refactor of the formatter to scale better later on
  pydocstringformatter/formatting.py
  pydocstringformatter/formatting/__init__.py
  pydocstringformatter/formatting/formatter.py
  pydocstringformatter/run.py
  pyproject.toml
Labels: enhancement

#18 Add a name and an optional attribute to Formatters
  .github/CONTRIBUTING.md
  pydocstringformatter/formatting/__init__.py
  pydocstringformatter/formatting/base.py
  pydocstringformatter/formatting/formatter.py
  tests/test_formatter.py
Labels: enhancement

#19 Print out ``diff`` instead of complete file for formatting changes
  pydocstringformatter/run.py
  pydocstringformatter/utils/__init__.py
  pydocstringformatter/utils/file_diference.py
  tests/data/format/no_changes/multi_line_variables.py.out
  tests/test_config.py
  tests/test_formatting.py
  tests/test_run.py
Labels: enhancement

#20 Add prettier to pre-commit and apply it
  .github/CONTRIBUTING.md
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  README.md
Labels: enhancement, Maintenance

#16 Reconfigure encoding of ``stdout`` to ensure emoji's can be displayed
  pydocstringformatter/run.py
  pydocstringformatter/utils/__init__.py
  pydocstringformatter/utils/output.py
  tests/test_utils.py
Labels: bug

#15 Make every formatter optional
  .github/CONTRIBUTING.md
  pydocstringformatter/run.py
  pydocstringformatter/utils/__init__.py
  pydocstringformatter/utils/argument_parsing.py
  tests/test_run.py
Labels: enhancement

#31 Add an ``exclude`` option to exclude files based on ``glob`` patterns
  README.md
  pydocstringformatter/configuration/arguments_manager.py
  pydocstringformatter/configuration/toml_parsing.py
  pydocstringformatter/configuration/validators.py
  pydocstringformatter/run.py
  pydocstringformatter/utils/find_python_file.py
  tests/data/config/exclude_match/pyproject.toml
  tests/data/config/exclude_match/test_package/incorrect_docstring.py
  tests/data/config/exclude_match_csv/pyproject.toml
  tests/data/config/exclude_match_csv/test_package/incorrect_docstring.py
  tests/data/config/exclude_match_csv_list/pyproject.toml
  tests/data/config/exclude_match_csv_list/test_package/incorrect_docstring.py
  tests/data/config/exclude_match_inner/pyproject.toml
  tests/data/config/exclude_match_inner/test_package/inner_dir/incorrect_docstring.py
  tests/data/config/exclude_non_match/pyproject.toml
  tests/data/config/exclude_non_match/test_package/incorrect_docstring.py
  tests/test_config.py
  tests/test_utils.py
Labels: enhancement
